tndata_backend/chat/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^debug/$',
        views.debug_messages,
        name='debug'
    ),
    url(
        r'^contacts/$',
        views.contacts,
        name='contacts'
    ),
    url(
        r'group/(?P<pk>\d+)-(?P<slug>.*)/$',
        views.group_chat_view,
        name='group-chat'
    ),
    url(
        r'(?P<recipient_id>\d+)/$',
        views.chat_view,
        name='chat'
    ),
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
]

tndata_backend/goals/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^my-content/$',
        views.MyContentView.as_view(),
        name='my-content'
    ),

    # Async file upload url
    # format:  /goals/<object_type>/<pk>/upload/
    # e.g. /goals/action/428/upload/
    # e.g. /goals/category/2/upload/
    url(
        r'^upload/(?P<object_type>\w+)/(?P<pk>\d+)/$',
        views.file_upload,
        name='file-upload'
    ),

    # Custom Packages
    url(
        r'^accept-enrollment/complete/$',
        views.AcceptEnrollmentCompleteView.as_view(),
        name='accept-enrollment-complete'
    ),
    url(
        r'^accept-enrollment/(?P<pk>\d+)/$',
        views.accept_enrollment,
        name='accept-enrollment'
    ),
    url(
        r'^packages/(?P<pk>\d+)/email/$',
        views.enrollment_cta_email,
        name='package-cta-email'
    ),
    url(
        r'^packages/(?P<pk>\d+)/report/$',
        views.package_report,
        name='package-report'
    ),
    url(
        r'^packages/(?P<pk>\d+)/reminder/$',
        views.enrollment_reminder,
        name='package-reminder'
    ),
    url(
        r'^packages/(?P<pk>\d+)/enroll/$',
        views.PackageEnrollmentView.as_view(),
        name='package-enroll'
    ),
    url(
        r'^packages/(?P<pk>\d+)/delete/$',
        views.PackageEnrollmentDeleteView.as_view(),
        name='package-enrollment-delete'
    ),
    url(
        r'^packages/(?P<pk>\d+)/calendar/$',
        views.package_calendar,
        name='package-calendar'
    ),
    url(
        r'^packages/(?P<package_id>\d+)/(?P<user_id>\d+)/$',
        views.package_enrollment_user_details,
        name='package-user-details'
    ),
    url(
        r'^packages/(?P<pk>\d+)/$',
        views.PackageDetailView.as_view(),
        name='package-detail'
    ),
    url(
        r'^packages/$',
        views.PackageListView.as_view(),
        name='package-list'
    ),

    # Create views
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/new-program/$',
        views.ProgramCreateView.as_view(),
        name='program-create'
    ),
    url(
        r'^new/organization/$',
        views.OrganizationCreateView.as_view(),
        name='organization-create'
    ),
    url(
        r'^new/categories/$',
        views.CategoryCreateView.as_view(),
        name='category-create'
    ),
    url(
        r'^new/goals/$',
        views.GoalCreateView.as_view(),
        name='goal-create'
    ),
    url(
        r'^new/action/$',
        views.ActionCreateView.as_view(),
        name='action-create'
    ),

    # Actions
    url(
        r'^actions/$',
        views.ActionListView.as_view(),
        name='action-list'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/disable-trigger/$',
        views.disable_trigger,
        name='action-disable-trigger'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.ActionPublishView.as_view(),
        name='action-publish'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.ActionTransferView.as_view(),
        name='action-transfer'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.ActionUpdateView.as_view(),
        name='action-update'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.ActionDeleteView.as_view(),
        name='action-delete'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.ActionDuplicateView.as_view(),
        name='action-duplicate'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.ActionDetailView.as_view(),
        name='action-detail'
    ),

    # Triggers
    url(
        r'^triggers/$',
        views.TriggerListView.as_view(),
        name='trigger-list'
    ),
    url(
        r'^triggers/(?P<pk>\d+)/$',
        views.TriggerDetailView.as_view(),
        name='trigger-detail'
    ),

    # Goals
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.GoalPublishView.as_view(),
        name='goal-publish'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.GoalTransferView.as_view(),
        name='goal-transfer'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.GoalUpdateView.as_view(),
        name='goal-update'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.GoalDeleteView.as_view(),
        name='goal-delete'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.GoalDuplicateView.as_view(),
        name='goal-duplicate'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.GoalDetailView.as_view(),
        name='goal-detail'
    ),
    url(
        r'^goals/$',
        views.GoalListView.as_view(),
        name='goal-list'
    ),

    # Categories
    url(
        r'^categories/$',
        views.CategoryListView.as_view(),
        name='category-list'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.CategoryPublishView.as_view(),
        name='category-publish'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.CategoryTransferView.as_view(),
        name='category-transfer'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.CategoryUpdateView.as_view(),
        name='category-update'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.CategoryDeleteView.as_view(),
        name='category-delete'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate-all/$',
        views.duplicate_content,
        name='duplicate-content'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.CategoryDuplicateView.as_view(),
        name='category-duplicate'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/reset-triggers/$',
        views.reset_default_triggers_in_category,
        name='category-reset-triggers'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.CategoryDetailView.as_view(),
        name='category-detail'
    ),

    # Organizations / Programs
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.ProgramUpdateView.as_view(),
        name='program-update'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.ProgramDeleteView.as_view(),
        name='program-delete'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.ProgramDetailView.as_view(),
        name='program-detail'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.OrganizationUpdateView.as_view(),
        name='organization-update'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.OrganizationDeleteView.as_view(),
        name='organization-delete'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<name_slug>.+)/add-member/$',
        views.organization_add_member,
        name='organization-add-member'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.OrganizationDetailView.as_view(),
        name='organization-detail'
    ),
    url(
        r'^programs/(?P<program_id>\d+)/add-member/$',
        views.program_add_member,
        name='program-add-member'
    ),
    url(
        r'^programs/$',
        views.ProgramListView.as_view(),
        name='program-list'
    ),
    url(
        r'^organizations/$',
        views.OrganizationListView.as_view(),
        name='organization-list'
    ),

    # Misc Debugging & Reports.
    url(
        r'^batch-assign-keywords/$',
        views.admin_batch_assign_keywords,
        name='batch-assign-keywords'
    ),
    url(
        r'^debug/$',
        views.DebugToolsView.as_view(),
        name='debug_tools'
    ),
    url(
        r'^debug-sequence/$',
        views.debug_sequence,
        name='debug_sequence'
    ),
    url(
        r'^debug-feed/$',
        views.debug_feed,
        name='debug_feed'
    ),
    url(
        r'^debug-priority-notifications/$',
        views.debug_priority_notifications,
        name='debug_priority_notifications'
    ),
    url(
        r'^debug-notifications/$',
        views.debug_notifications,
        name='debug_notifications'
    ),
    url(
        r'^debug-progress/$',
        views.debug_progress,
        name='debug_progress'
    ),
    url(
        r'^reports/organization/(?P<pk>\d+)/membership-download/$',
        views.organization_membership_download,
        name='organization-membership-download'
    ),
    url(
        r'^reports/organization/(?P<pk>\d+)/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/organization/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/triggers/$',
        views.report_triggers,
        name='report-triggers'
    ),
    url(
        r'^reports/popular/$',
        views.ReportPopularView.as_view(),
        name='report-popular'
    ),
    url(
        r'^reports/actions/$',
        views.report_actions,
        name='report-actions'
    ),
    url(
        r'^reports/authors/$',
        views.report_authors,
        name='report-authors'
    ),
    url(
        r'^reports/engagement/$',
        views.report_engagement,

tndata_backend/notifications/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^send/$', views.send_message, name='send'),
    url(r'^cancel-jobs/$', views.cancel_all_jobs, name='cancel-jobs'),
    url(r'^cancel-job/$', views.cancel_job, name='cancel-job'),
    url(r'^(?P<message_id>\d+)/$', views.view_message, name='view'),
    url(
        r'^(?P<user_id>\d+)/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$',
        views.userqueue,
        name='userqueue'
    ),

]

tndata_backend/officehours/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^$',
        views.index,
        name='index'
    ),
    url(
        r'^login/$',
        views.login,
        name='login'
    ),
    url(
        r'^add-code/$',
        views.add_code,
        name='add-code'
    ),
    url(
        r'^add-hours/$',
        views.add_hours,
        name='add-hours'
    ),
    url(
        r'^add-course/$',
        views.add_course,
        name='add-course'
    ),
    url(
        r'^contact-info/$',
        views.contact_info,
        name='contact-info'
    ),
    url(
        r'^phone/$',
        views.phone_number,
        name='phone-number'
    ),
    url(
        r'^hours/(?P<pk>\d+)/delete/$',
        views.delete_officehours,
        name='delete-officehours'
    ),
    url(
        r'^hours/(?P<pk>\d+)/$',
        views.officehours_details,
        name='officehours-details'
    ),
    url(
        r'^schedule/(?P<pk>\d+)/share/$',
        views.share_course,
        name='share-course'
    ),
    url(
        r'^schedule/(?P<pk>\d+)/delete/$',
        views.delete_course,
        name='delete-course'
    ),
    url(
        r'^schedule/(?P<pk>\d+)/$',
        views.course_details,
        name='course-details'
    ),
    url(
        r'^schedule/$',
        views.schedule,
        name='schedule'
    ),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^help/$', views.HelpView.as_view(), name='help'),
    url(r'^create-account/$', views.create_account, name='create-account'),
]

tndata_backend/officehours/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms_foundation.layout.fields import Field


class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=256)
    email = forms.EmailField()
    phone = forms.CharField(max_length=256)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False  # Don't generate <form> tags

        self.helper.layout = Layout(
            Field('your_name'),
            Field('email'),
            Field('phone'),
        )

tndata_backend/officehours/templates/officehours/_off_canvas.html
{% load staticfiles %}

{% with loggedin=user.is_authenticated %}
  {% if loggedin %}
    <h5>Hi, {{ user.first_name }}.</h5>
  {% else %}
    <h5>Hi, there.</h5>
  {% endif %}

  {% with avatar=user.userprofile.google_image %}
    {% if avatar %}
      <p><img src="{{ avatar }}" class="thumbnail"></p>
    {% else %}
      <p>
        <i class="fa fa-user-circle-o fa-5x"></i>
      </p>
    {% endif %}
  {% endwith %}

  <nav>
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-home"></i>
        <a href="{% url 'officehours:index' %}">Home</a>
      </li>
      {% if loggedin %}
      <li>
        <i class="fa-li fa fa-calendar"></i>
        <a href="{% url 'officehours:schedule' %}">Schedule</a>
      </li>
      <li>
        <i class="fa-li fa fa-plus-circle"></i>
        <a href="{% url 'officehours:add-code' %}">Add a Code</a>
      </li>
      <li>
        <i class="fa-li fa fa-mobile"></i>
        <a href="{% url 'officehours:phone-number' %}">Phone</a>
      </li>
      <li>
        <i class="fa-li fa fa-address-book-o"></i>
        <a href="{% url 'chat:contacts' %}">Contacts</a>
      </li>
      {% comment %}
      <li>
        <i class="fa-li fa fa-info-circle"></i>
        <a href="{% url 'officehours:help' %}">Help</a>
      </li>
      {% endcomment %}
      <li>
        <i class="fa-li fa fa-sign-out"></i>
        <a onclick="signOut();">Log out</a>
      </li>
      {% else %}
      <li>
        <i class="fa-li fa fa-sign-in"></i>
        <a onclick="signIn();">Log in</a>
      </li>
      {% endif %}
    </ul>
  </nav>
{% endwith %}

tndata_backend/officehours/templates/officehours/add_code.html
{% extends "officehours/base.html" %}

{% block content %}

<div class="column column-block">
  <div class="callout">
  <form action="{% url 'officehours:add-code' %}" method="post">{% csrf_token %}
    <h3>Add your Code</h3>
    <label>Add your code, here
      <input type="text" placeholder="XJ47" aria-describedby="codeHelpText"
             id="code"
             name="code"
             size="4"
             maxlength="4"
             minlength="4"
             class="code-input"/>
    </label>
    <p class="help-text" id="codeHelpText">
      Your teacher will share a 4-character code with you. Enter it here to
      ensure you're added to the correct class.
    </p>
    <input type="hidden" id="id_next" name="next" value="{{next_url}}"/>
    <button class="button">Add code</button>
    </form>
  </div> {# /.callout #}
</div>
{% endblock %}


{% block bodyjs %}
<script type="text/javascript">

$(document).ready(function() {
  // Auto-advance the Code inputs.
  $(".code-input").keyup(function() {
      $(this).val($(this).val().toUpperCase());
  });
});
</script>
{% endblock %}

tndata_backend/officehours/templates/officehours/add_course.html
{% extends "officehours/base.html" %}
{% load staticfiles %}

{% block extrahead %}
  <script src="{% static 'js/moment.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'timepicker/jquery.timepicker.css' %}">
{% endblock %}


{% block content %}
<div class="column column-block">
  <div class="callout">
    <form action="{% url 'officehours:add-course' %}" method="post">
      {% csrf_token %}
      <h3>Add your Course</h3>

      <label for="id_coursename">Course Name
        <input type="text"
               name="coursename"
               placeholder="Intro to History, COMP 1500, etc"
               {% if coursename %}value="{{coursename}}"{% endif %}
               id="id_coursename">
      </label>
      {% if coursename_error %}<p>{{ coursename_error }}</p>{% endif %}

      <label for="id_coursetime">Course Meeting Time
        <input type="text"
               placeholder="8:45 am"
               name="coursetime"
               {% if coursetime %}value="{{coursetime|date:"g:i A"|lower}}"{% endif %}
               id="id_coursetime">
      </label>
      {% if coursetime_error %}<p>{{ coursetime_error }}</p>{% endif %}

      <label for="id_location">Location
        <input type="text"
               id="id_location"
               placeholder="Building, room number, etc"
               {% if location %}value="{{location}}"{% endif %}
               name="location">
      </label>
      {% if location_error %}<p>{{ location_error }}</p>{% endif %}

      <fieldset class="fieldset">
        <legend>Select the days on which this course meets</legend>
        {% for day in day_choices %}
          <input type="checkbox"
                 id="course-day-{{ day|lower }}"
                 name="{{ day }}"
                 {% if day in selected_days %}checked="checked"{% endif %}
                 data-day="{{ day }}">
          <label for="course-day-{{ day|lower }}">{{ day }}</label>
          <br/>
        {% endfor %}
      </fieldset>
      <button class="button" type="submit"
              name="another" value="true">Add another</button>
      <button class="button" type="submit"
              name="share" value="true">Share</button>
    </form>
  </div> {# /.callout #}
</div> {# /.column #}

{% endblock %}


{% block bodyjs %}
<script src="{% static 'timepicker/jquery.timepicker.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $("#id_coursetime").timepicker({
    'scrollDefault': 'now',
    'timeFormat': 'g:i a',
  });
});
</script>
{% endblock %}

tndata_backend/officehours/templates/officehours/add_hours.html
{% extends "officehours/base.html" %}
{% load staticfiles %}

{% block extrahead %}
  <script src="{% static 'js/moment.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'timepicker/jquery.timepicker.css' %}">
{% endblock %}

{% block content %}

{# Would this even work on mobile browsers? #}
{# ---- TODO: <p><input type="time" name="testing"></p> ---- #}

<div class="column column-block">
	<div class="callout">
		<h3>Office Hours</h3>
    <form action="{% url 'officehours:add-hours' %}" method="post">
      {% csrf_token %}
      <ul class="no-bullet">
      {% for day in day_choices %}
        <li>
          <input type="checkbox"
                 class="day-selector"
                 id="officehours-day-{{ day|lower }}"
                 name="{{ day }}"
                 {% if day in selected_days %}checked="checked"{% endif %}
                 data-day="{{ day }}">
          <label for="officehours-day-{{ day|lower }}">{{ day }}</label>

          {# --- time-row -------------------------------------------------- #}
          <div class="time-wrapper time-row row">
            <div class="small-2 columns">
              <label for="id_from_time-{{ day|lower }}"
                     class="text-left middle">From</label>
            </div>
            <div class="small-4 columns">
              <input id="id_from_time-{{ day|lower }}"
                     class="timeinput"
                     name="from_time-{{ day|lower }}"
                     type="text"
                     placeholder="10:30 am"/>
            </div>
            <div class="small-2 columns">
              <label for="id_to_time-{{day|lower}}"
                     class="text-left middle">To</label>
            </div>
            <div class="small-4 columns">
              <input id="id_to_time-{{day|lower}}"
                     name="to_time-{{day|lower }}"
                     class="timeinput"
                     type="text"
                     placeholder="1:30 pm"/>
            </div>
          </div>
          {# --- /time-row ------------------------------------------------- #}

          <div class="row time-wrapper">
            <div class="small-12 columns text-right">
              <a href="#" class="button secondary tiny add-time-row">
                <i class="fa fa-plus"></i>
                Add Times
              </a>
            </div>
          </div>
        </li>
      {% endfor %}
      </ul>

     <button class="button"
              type="submit"
              name="next"
              value="true">Save</button>
    </form>
  </div> {# /.callout #}
</div> {# /.column #}
{% endblock %}


{% block bodyjs %}
<script src="{% static 'timepicker/jquery.timepicker.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
  // dynamically add timepicker to all .timeinput elements.
  $('body').on('focus', ".timeinput", function() {
    $(this).timepicker({
      'scrollDefault': 'now',
      'timeFormat': 'g:i a',
    });
  });

  // Hide all time-wrappers by default.
  $(".time-wrapper").hide();

  // When we click a day, display the time-wrappers.
  $(".day-selector").change(function(evt) {
    $(this).parent().children(".time-wrapper").show();
  });

  // when we click the button to add a new input row, do so.
  $(".add-time-row").click(function(evt) {
    evt.preventDefault();
    var inputRow = $(this).parents("li").children(".time-row")[0];
    var inputClone = $(inputRow).clone();
    inputClone.insertBefore($(this));
  });

});
</script>
{% endblock %}

tndata_backend/officehours/templates/officehours/contact.html
{% extends "officehours/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="columns column-block">
  <div class="callout">
    <h1>Get in touch</h1>
    <p>Need help or have feedback for this app?
       Contact us using the button below:</p>
    <p>
      <a class="button" href="mailto:feeback@tndata.org" target="_blank">
      Get in Touch</a>
    </p>
  </div>
</div>
{% endblock %}

tndata_backend/officehours/templates/officehours/contact_info.html
{% extends "officehours/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
{# Teacher Info #}
<div class="column column-block">
  <div class="callout">
    <h3>Add your information</h3>
    <form action="{% url 'officehours:contact-info' %}" method="post">
      {% csrf_token %}
      {% crispy form %}
      <button class="button" type="submit">Next</button>
    </form>
  </div> {# /.callout #}
</div> {# /.column #}
{% endblock %}

tndata_backend/officehours/templates/officehours/course_details.html
{% extends "officehours/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="column column-block" id="teacher-schedule">
  <div class="callout">
    <h2>{{ course.name }}
      <small>&mdash;
        <code class="stat">{{ course.code }}</code>
      </small>
    </h2>
    {% with students=course.students.all %}
    <table class="stack">
      <caption>{{ students.count }} students in this course</caption>
      <thead>
        <tr>
          <th>Student Name</th>
          <th>Contact Info</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for student in students %}
        {% with name=student.get_full_name %}
        <tr>
          <td><strong>{{ name|default:"-" }}</strong></td>
          <td>
            <a href="mailto:{{ student.email }}">{{ student.email }}</a>
            {% if student.userprofile.phone %}
              <br/>{{ student.userprofile.phone }}
            {% endif %}
          </td>
          <td>
            <a href="{% url 'chat:chat' student.id %}"
               class="button secondary tiny">
                  <i class="fa fa-comment-o"></i> Chat</a>
          </td>
        </li>
        {% endwith %}
      {% endfor %}
      </tbody>
    </table>
    {% endwith %}
    <hr/>
    <p>
      <a href="{{ course.get_delete_url }}"
         class="button alert float-right"><i class="fa fa-trash"></i> Delete Course</a>
      <a href="#" class="button" id="message-all" disabled>Message All Students</a>
    </p>
  </div>
</div>

{% endblock %}

tndata_backend/officehours/templates/officehours/delete_officehours.html
{% extends "officehours/base.html" %}

{% block content %}

<div class="column column-block">
  <div class="callout">
    <form action="{{ hours.get_delete_url }}" method="post">
      {% csrf_token %}
      <h2>Office Hours</h2>

      <ul class="no-bullet">
      {% for day, hours_list in hours.get_schedule %}
        <li>
          <strong>{{ day }}</strong>
          <ul>
          {% for obj in hours_list %}
            <li>{{ obj.from }} - {{ obj.to }}</li>
          {% endfor %}
          </ul>
        </li>
      {% endfor %}
      </ul>
      <p>These office hours automatically expire in
         {{ hours.expires_on|timeuntil }} on {{ hours.expires_on }}.</p>
      <hr/>


      <div class="callout warning">
        <div class="row">
          <div class="small-2 column">
            <i class="fa fa-warning fa-2x"></i>
          </div>
          <div class="small-10 column">
            Are you sure you want to permanently delete these hours?
          </div>
        </div>
      </div>

      <p>
        <input type="submit"
               name="confirm"
               class="button alert"
               value="Yes, Delete Office Hours"/>
      </p>
    </form>
  </div>
</div>
{% endblock %}

tndata_backend/officehours/templates/officehours/officehours_details.html
{% extends "officehours/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="column column-block" id="teacher-schedule">
  <div class="callout">
    <h2>Office Hours</h2>

    <ul class="no-bullet">
    {% for day, hours_list in hours.get_schedule %}
      <li>
        <strong>{{ day }}</strong>
        <ul>
        {% for obj in hours_list %}
          <li>{{ obj.from }} - {{ obj.to }}</li>
        {% endfor %}
        </ul>
      </li>
    {% endfor %}
    </ul>
    <p>These office hours automatically expire in
       {{ hours.expires_on|timeuntil }} on {{ hours.expires_on }}.</p>
    <hr/>
    <p class="clearfix">
      <a href="{{ hours.get_delete_url }}"
         class="button alert float-right"><i class="fa fa-trash"></i> Delete Hours</a>
    </p>
  </div>
</div>

{% endblock %}

tndata_backend/officehours/templates/officehours/phone_number.html
{% extends "officehours/base.html" %}

{% block content %}

<div class="column column-block">
  <div class="callout">
    <form action="{% url 'officehours:phone-number' %}" method="post">{% csrf_token %}
      <h3>Set your mobile number</h3>

      {% if error %}<p>{{ error }}</p>{% endif %}
      <label for="id_phone">Phone Number
        <input value="{{ phone|default:'' }}"
               type="text"
               id="id_phone"
               placeholder="901-555-1234"
               name="phone"
               aria-describedby="codeHelpText">
      </label>
      <p class="help-text" id="codeHelpText">
        Add your cell phone, and we'll periodically text
        you with important information.
      </p>
      <button class="button" type="submit">Save</button>
    </form>
  </div>
</div>
{% endblock %}