tndata_backend/chat/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^debug/$',
        views.debug_messages,
        name='debug'
    ),
    url(
        r'^contacts/$',
        views.contacts,
        name='contacts'
    ),
    url(
        r'group/(?P<pk>\d+)-(?P<slug>.*)/$',
        views.group_chat_view,
        name='group-chat'
    ),
    url(
        r'(?P<recipient_id>\d+)/$',
        views.chat_view,
        name='chat'
    ),
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
]

tndata_backend/goals/urls.py
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^my-content/$',
        views.MyContentView.as_view(),
        name='my-content'
    ),

    # Async file upload url
    # format:  /goals/<object_type>/<pk>/upload/
    # e.g. /goals/action/428/upload/
    # e.g. /goals/category/2/upload/
    url(
        r'^upload/(?P<object_type>\w+)/(?P<pk>\d+)/$',
        views.file_upload,
        name='file-upload'
    ),

    # Custom Packages
    url(
        r'^accept-enrollment/complete/$',
        views.AcceptEnrollmentCompleteView.as_view(),
        name='accept-enrollment-complete'
    ),
    url(
        r'^accept-enrollment/(?P<pk>\d+)/$',
        views.accept_enrollment,
        name='accept-enrollment'
    ),
    url(
        r'^packages/(?P<pk>\d+)/email/$',
        views.enrollment_cta_email,
        name='package-cta-email'
    ),
    url(
        r'^packages/(?P<pk>\d+)/report/$',
        views.package_report,
        name='package-report'
    ),
    url(
        r'^packages/(?P<pk>\d+)/reminder/$',
        views.enrollment_reminder,
        name='package-reminder'
    ),
    url(
        r'^packages/(?P<pk>\d+)/enroll/$',
        views.PackageEnrollmentView.as_view(),
        name='package-enroll'
    ),
    url(
        r'^packages/(?P<pk>\d+)/delete/$',
        views.PackageEnrollmentDeleteView.as_view(),
        name='package-enrollment-delete'
    ),
    url(
        r'^packages/(?P<pk>\d+)/calendar/$',
        views.package_calendar,
        name='package-calendar'
    ),
    url(
        r'^packages/(?P<package_id>\d+)/(?P<user_id>\d+)/$',
        views.package_enrollment_user_details,
        name='package-user-details'
    ),
    url(
        r'^packages/(?P<pk>\d+)/$',
        views.PackageDetailView.as_view(),
        name='package-detail'
    ),
    url(
        r'^packages/$',
        views.PackageListView.as_view(),
        name='package-list'
    ),

    # Create views
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/new-program/$',
        views.ProgramCreateView.as_view(),
        name='program-create'
    ),
    url(
        r'^new/organization/$',
        views.OrganizationCreateView.as_view(),
        name='organization-create'
    ),
    url(
        r'^new/categories/$',
        views.CategoryCreateView.as_view(),
        name='category-create'
    ),
    url(
        r'^new/goals/$',
        views.GoalCreateView.as_view(),
        name='goal-create'
    ),
    url(
        r'^new/action/$',
        views.ActionCreateView.as_view(),
        name='action-create'
    ),

    # Actions
    url(
        r'^actions/$',
        views.ActionListView.as_view(),
        name='action-list'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/disable-trigger/$',
        views.disable_trigger,
        name='action-disable-trigger'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.ActionPublishView.as_view(),
        name='action-publish'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.ActionTransferView.as_view(),
        name='action-transfer'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.ActionUpdateView.as_view(),
        name='action-update'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.ActionDeleteView.as_view(),
        name='action-delete'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.ActionDuplicateView.as_view(),
        name='action-duplicate'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.ActionDetailView.as_view(),
        name='action-detail'
    ),

    # Triggers
    url(
        r'^triggers/$',
        views.TriggerListView.as_view(),
        name='trigger-list'
    ),
    url(
        r'^triggers/(?P<pk>\d+)/$',
        views.TriggerDetailView.as_view(),
        name='trigger-detail'
    ),

    # Goals
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.GoalPublishView.as_view(),
        name='goal-publish'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.GoalTransferView.as_view(),
        name='goal-transfer'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.GoalUpdateView.as_view(),
        name='goal-update'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.GoalDeleteView.as_view(),
        name='goal-delete'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.GoalDuplicateView.as_view(),
        name='goal-duplicate'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.GoalDetailView.as_view(),
        name='goal-detail'
    ),
    url(
        r'^goals/$',
        views.GoalListView.as_view(),
        name='goal-list'
    ),

    # Categories
    url(
        r'^categories/$',
        views.CategoryListView.as_view(),
        name='category-list'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.CategoryPublishView.as_view(),
        name='category-publish'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.CategoryTransferView.as_view(),
        name='category-transfer'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.CategoryUpdateView.as_view(),
        name='category-update'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.CategoryDeleteView.as_view(),
        name='category-delete'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate-all/$',
        views.duplicate_content,
        name='duplicate-content'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.CategoryDuplicateView.as_view(),
        name='category-duplicate'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/reset-triggers/$',
        views.reset_default_triggers_in_category,
        name='category-reset-triggers'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.CategoryDetailView.as_view(),
        name='category-detail'
    ),

    # Organizations / Programs
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.ProgramUpdateView.as_view(),
        name='program-update'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.ProgramDeleteView.as_view(),
        name='program-delete'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.ProgramDetailView.as_view(),
        name='program-detail'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.OrganizationUpdateView.as_view(),
        name='organization-update'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.OrganizationDeleteView.as_view(),
        name='organization-delete'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<name_slug>.+)/add-member/$',
        views.organization_add_member,
        name='organization-add-member'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.OrganizationDetailView.as_view(),
        name='organization-detail'
    ),
    url(
        r'^programs/(?P<program_id>\d+)/add-member/$',
        views.program_add_member,
        name='program-add-member'
    ),
    url(
        r'^programs/$',
        views.ProgramListView.as_view(),
        name='program-list'
    ),
    url(
        r'^organizations/$',
        views.OrganizationListView.as_view(),
        name='organization-list'
    ),

    # Misc Debugging & Reports.
    url(
        r'^batch-assign-keywords/$',
        views.admin_batch_assign_keywords,
        name='batch-assign-keywords'
    ),
    url(
        r'^debug/$',
        views.DebugToolsView.as_view(),
        name='debug_tools'
    ),
    url(
        r'^debug-sequence/$',
        views.debug_sequence,
        name='debug_sequence'
    ),
    url(
        r'^debug-feed/$',
        views.debug_feed,
        name='debug_feed'
    ),
    url(
        r'^debug-priority-notifications/$',
        views.debug_priority_notifications,
        name='debug_priority_notifications'
    ),
    url(
        r'^debug-notifications/$',
        views.debug_notifications,
        name='debug_notifications'
    ),
    url(
        r'^debug-progress/$',
        views.debug_progress,
        name='debug_progress'
    ),
    url(
        r'^reports/organization/(?P<pk>\d+)/membership-download/$',
        views.organization_membership_download,
        name='organization-membership-download'
    ),
    url(
        r'^reports/organization/(?P<pk>\d+)/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/organization/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/triggers/$',
        views.report_triggers,
        name='report-triggers'
    ),
    url(
        r'^reports/popular/$',
        views.ReportPopularView.as_view(),
        name='report-popular'
    ),
    url(
        r'^reports/actions/$',
        views.report_actions,
        name='report-actions'
    ),
    url(
        r'^reports/authors/$',
        views.report_authors,
        name='report-authors'
    ),
    url(
        r'^reports/engagement/$',
        views.report_engagement,
        name='report-engagement'
    ),
    url(
        r'^reports/$',
        views.ReportsView.as_view(),

tndata_backend/notifications/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^send/$', views.send_message, name='send'),
    url(r'^cancel-jobs/$', views.cancel_all_jobs, name='cancel-jobs'),
    url(r'^cancel-job/$', views.cancel_job, name='cancel-job'),
    url(r'^(?P<message_id>\d+)/$', views.view_message, name='view'),
    url(
        r'^(?P<user_id>\d+)/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$',
        views.userqueue,
        name='userqueue'
    ),

]

tndata_backend/chat/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from .managers import ChatMessageManager


class ChatMessage(models.Model):
    """A persisted chat message."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        help_text="Message sender"
    )
    # -------------------------------------------------------------------------
    # NOTE: Right now, 1-1 chat rooms are of the form `chat-<userid>-<userid>`.
    # See the `set_chatmessage_recipients` post_save handler to see how
    # recipients get saved.
    # -------------------------------------------------------------------------
    recipients = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='chatmessages_received',
        help_text='Message recipient(s)'
    )
    room = models.CharField(max_length=256, default="", db_index=True)
    text = models.TextField(default="")
    read = models.BooleanField(default=False)

    # NOTE: This is an md5 digest of the message's author + text + creation time.
    # It's used as an intial ID for the message, which we need to know prior
    # to the object's creation time (for read receipts)
    digest = models.CharField(max_length=32, blank=True, default='', db_index=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Chat Message"
        verbose_name_plural = "Chat Messages"

    objects = ChatMessageManager()


@receiver(post_save, sender=ChatMessage, dispatch_uid='set-chatmessage-recipients')
def set_chatmessage_recipients(sender, instance, created, **kwargs):
    """After a message is saved, we try to set the Users who would have been
    the message's recipients. This is not done in the websocket consumer,
    because we don't have all the recipient info available.

    Here's the strategy:

    1. Person-to-person messages have a chat room of the form `chat-<id>-<id>`.
       If that's the kind of message we get, we'll look up those users.
    2. TODO: Otherwise, we'll pull all the messages from the related Chat Group

    """
    User = get_user_model()

    if instance and instance.room.startswith("chat-"):
        ids = instance.room[len("chat-"):].split('-')
        users = User.objects.filter(pk__in=ids)
        users = users.exclude(pk=instance.user.id)
        for user in users:
            instance.recipients.add(user)

    # TODO: do this for groups.


class ChatGroup(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)  # Group "owner"
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(max_length=256, unique=True)

    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="chatgroup_member"
    )
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Chat Group"
        verbose_name_plural = "Chat Group"

    @property
    def members_count(self):
        return self.members.all().count()

    def get_absolute_url(self):
        return reverse("chat:group-chat", args=[self.pk, self.slug])

tndata_backend/notifications/forms.py
from django import forms
from . models import GCMMessage


class GCMMessageForm(forms.ModelForm):
    class Meta:
        model = GCMMessage
        fields = ['title', 'message', 'content_type', 'object_id']

tndata_backend/notifications/templates/notifications/base.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}Notifications{% endblock %}

{% block head %}
{# Datatables' Foundation CSS (see bodyjs block for the JS) #}
<link rel="stylesheet" href="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/foundation/dataTables.foundation.css" />
<style type="text/css">
  pre {background-color: #eee; padding:0.5em; margin:0.5em; margin-bottom:1em;}
</style>
{% endblock %}


{% block topnav %}
  <div class="sticky">
  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" title="Project Home"><i class="fa fa-chevron-left"></i></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    {# Right Nav Section #}
    <ul class="right">
      <li class="divider"></li>
      <li><a href="{% url 'haystack_search' %}">
        <i class="fa fa-search"></i></a></li>
      <li class="divider"></li>
      <li><a href="{% url 'userprofile:index' %}">
        <i class="fa fa-user"></i> Account</a></li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="/admin/"><i class="fa fa-unlock"></i> Admin</a>
        <ul class="dropdown">
          <li><a href="{% url 'goals:debug_progress' %}">
            User Progress</a></li>
          <li><a href="{% url 'goals:debug_notifications' %}">
            User Feed</a></li>
          <li><a href="{% url 'notifications:dashboard' %}">
            Notification Dashboard</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li><a href="{% url 'logout' %}">
        <i class="fa fa-sign-out"></i> Sign Out</a></li>
    </ul>

    {# Left Nav Section #}
    <ul class="left">
      <li class="divider"></li>
      <li><a href="/rq/">RQ</a></li>
      <li class="divider"></li>
    </ul>
  </section>
  </nav>
  </div>
{% endblock %}


{% block body %}
  <div class="row">
    <div class="large-12 small-12 columns">
      <ul class="breadcrumbs">
      <li><a href="{% url 'notifications:dashboard' %}">Notification Dashboard</a></li>
      {% block breadcrumbs %}{% endblock %}
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="large-12 small-12 columns">
    {% block content %}{% endblock %}
    </div>
  </div>
{% endblock %}


{% block bodyjs %}
  {{ block.super }}
  {# Include DataTables Core and Foundation-specific JS #}
  <script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
  <script src="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/foundation/dataTables.foundation.js"></script>
  <script>
  $(document).ready(function() {
    // Apply datatables to all .object-list tables.
    // And include an initial search/filter value if applicable.
    var table = $("table.object-list")
    var initial = table.data("search");
    if(initial) {
      initial = initial.split("@")[0];
    }
    var table = table.DataTable({paging: false});

    if(initial) {
      table.search(initial);
      table.draw();
    }
  });
  </script>
{% endblock %}

tndata_backend/notifications/templates/notifications/index.html
{% extends "notifications/base.html" %}
{% load tz %}
{% load redis_metric_tags %}


{% block content %}
  {# Ask for UserQueue data #}

  <form method="get">
    <fieldset><legend>User Queue Details</legend>
      <div class="row">
        <div class="large-6 medium-6 small-12 columns">
          <input type="text" placeholder="user@email.com"
                 id="id_user" name="user"
                 value="{{ selected_user.email|default:'' }}"/>
          <input type="date" id="id_date" name="date"
                 value="{{ selected_date|date:"Y-m-d" }}"/>
          <button type="submit" class="button">Display</button>
        </div>
        <div class="large-6 medium-6 small-12 columns">

          {% if user_queues and devices == 0 %}
            <div data-alert class="alert-box warning">This user has no
            registered devices!</div>
          {% endif %}
          {# Link to the test notification sending form #}
          <p><a href="{% url 'notifications:send' %}"
            class="button pull-right">Send Push Notification</a></p>

        {% for user_queue in user_queues %}
          <div class="panel">
          {# Display the count key first. #}
          {% for key, values in user_queue.items %}
            {% if 'count' in key %}
              <h3>{{ key|cut:":count" }} <small>{{ values }} items</small></h3>
            {% endif %}
          {% endfor %}

          {# then the rest #}
          {% for key, values in user_queue.items %}
            {% if 'count' not in key %}
              <p><strong>{{ key }}
                <small>{{ values|length }} items</small></strong></p>
              <ul>
              {% for value in values %}
                <li>
                  <a data-tooltip aria-haspopup="true"
                     class="has-tip tip-top job-link"
                     style="color:#008CBA;font-weight:normal;cursor:help"
                     {% comment %}

                      ugh. this is awful but I've already wasted too
                      much time on this

                      Find related message info & show it in a tooltip

                     {% endcomment %}
                     {% for job, scheduled_for, message_data in jobs %}
                     {% if job.id == value %}
                     title="{{ message_data.title }} / {{ message_data.message }}"
                     {% endif %}
                     {% endfor %}
                     target="_blank"
                     href="/admin/notifications/gcmmessage/?q={{ value }}">
                  {{ value }}</a>
                </li>
              {% endfor %}
              </ul>
            {% endif %}
          {% endfor %}
          </div>
        {% endfor %}
        </div>
      </div>
    </fieldset>
  </form>

  {# display a redis-metrics chart of sent messages #}
  <h2>Notifications <small>{{ num_jobs }} total scheduled messages</small></h2>
  {% aggregate_history metrics %}

  <h3>Queued Messages</h3>
  {% with user_count=jobs|length %}
  {% if user_count %}
  <table class="object-list"{% if email %} data-search="{{ email }}"{% endif %}>
    <caption>{{ user_count }} Enqueued Messages</caption>
    <thead>
      <tr>
        <th>User</th>
        <th>Deliver</th>
        <th>Age</th>
        <th>Content</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for job, scheduled_for, message_data in jobs %}
      <tr>
        <td>
          {# Clicking the user's email shows their queue for the date #}
          {% if message_data.email %}
          <a href="{% url 'notifications:userqueue' message_data.user_id message_data.date_string %}" class="userqueue">
            {{ message_data.email|truncatechars:15 }}
          </a>
          {% endif %}
        </td>
        <td>
          {% with deliver_on=scheduled_for|localtime %}
            {{ deliver_on}}
            <small>{{ deliver_on|timeuntil }}</small>
          {% endwith %}
        </td>
        <td>{{ job.created_at|localtime|timesince }}</td>
        <td>
          <strong>{{ message_data.title }}</strong>
          <br/>{{ message_data.message }}
          {% if message_data.id %}
            <small>(
            <a href="/admin/notifications/gcmmessage/{{ message_data.id }}/"
              target="_blank"><i class="fa fa-external-link-square"></i> admin</a>
            )</small>
          {% endif %}
          <br/>
          <small>Job ID: <a href="/rq/queues/0/{{ job.id }}">{{ job.id }}</a></small>
        </td>
        <td>
          <form action="{% url 'notifications:cancel-job' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="job_id" value="{{ job.id }}"/>
            <button type="submit"
                    class="has-tip button tiny alert"
                    data-tooltip
                    aria-haspopup="true"
                    title="Cancel this Notification">
              <i class="fa fa-ban"></i>
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>Search for a user to view their queued messages</p>
  {% endif %}
  {% endwith %}


  <hr/>
  <div class="panel clearfix">
    <h3>DANGER</h3>
    <div class="pull-right" style="margin-left:1em;">
      <form action="{% url 'notifications:cancel-jobs' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear Notification Queue"
          class="button alert"/>
        <label for="id_orphaned">Orphaned Only?
          <input type="checkbox" name="orphaned" id="id_orphaned" />
        </label>
      </form>
    </div>
    <p><i class="fa fa-warning"></i> This button will remove all scheduled
    messages from the notification queue. Select <em>Orphaned Only</em>
    to remove the notifications that do not have a corresponding
    <code>GCMMessage</code> object.</p>
  </div>

  <div id="queueModal" class="reveal-modal"
       data-reveal aria-labelledby="modalTitle"
       aria-hidden="true" role="dialog">
    <h2 id="modalTitle"></h2>
    <dl>
      <dt>Total</dt><dd id="queueTotal"></dd>
      <dt>Low</dt><dd><ul id="queueLow"></ul></dd>
      <dt>Medium</dt><dd><ul id="queueMedium"></ul></dd>
      <dt>High</dt><dd><ul id="queueHigh"></ul></dd>
    </dl>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  </div>
{% endblock %}


{% block bodyjs %}
  {{ block.super }}
  <script type="text/javascript">

  var makeQueueList = function(items) {
    // Given an array of items, return an HTML string contining <li>-items
    var content = '';
      for(var i=0; i < items.length; i++) {
        content += '<li><a href="/rq/queues/0/' +
          items[i] + '/">' + items[i] + '</a></li>';
    }
    return content;
  }

  $(document).ready(function() {
    $(".userqueue").click(function(e) {
      e.preventDefault();
      $.get($(this).prop('href'), function(data) {
        console.log(data);
        if(data) {
          $("#modalTitle").text(data.user + " " + data.date);
          $("#queueTotal").text(data.count);
          $("#queueLow").html(makeQueueList(data.low));
          $("#queueMedium").html(makeQueueList(data.medium));
          $("#queueMedium").html(makeQueueList(data.high));
          $('#queueModal').foundation('reveal', 'open');
        }
      });
    });
  });
  </script>
{% endblock %}

tndata_backend/notifications/templates/notifications/send_message.html
{% extends "notifications/base.html" %}

{% block breadcrumbs %}
  <li class="current">Send</li>
{% endblock %}

{% block content %}

  {% if form.errors %}
    {{ form.errors }}
  {% endif %}
  <form method="post" action="{% url 'notifications:send' %}">{% csrf_token %}
    <fieldset><legend>Send a Push Notificatioan</legend>
      {{ form.as_p }}
      <p><input type="submit" value="Send" class="button"/></p>
    </fieldset>
  </form>

{% endblock %}

tndata_backend/notifications/templates/notifications/view_message.html
{% extends "notifications/base.html" %}


{% block breadcrumbs %}
  <li><a href="{% url 'notifications:send' %}">Send</a></li>
  <li class="current">Message</li>
{% endblock %}

{% block content %}

  <h1>Message Details</h1>
  <p>Message id <code>{{ message.id }}</code> to <code>{{ message.user }}</code>.</p>

  <h2>Payload</h2>
  <pre>{{ message.content|pprint }}</pre>

  <h2>Response Information</h2>
  <p>Response Code: {{ message.response_code }}</p>
  <p>Response text:</p><pre>{{ message.response_text|pprint}}</pre>
  <p>Response dataa:</p><pre>{{ message.response_data|pprint}}</pre>

  <h2>Devices</h2>
  <p>Android Devices:</p><pre>{{ message.android_devices|pprint }}</pre>
  <p>iOS Devices:</p><pre>{{ message.ios_devices|pprint }}</pre>

  <h2>Misc</h2>
  <p>Expiration: {{ message.expires_on }}</p>
  <p>Priority: {{ message.get_priority_display }}</p>
  <p>Queue ID: {{ message.queeu_id }}</p>
  <p>Content Type / Object ID: {{ message.content_type.name }} / {{ message.object_id }}</p>
  <p>Created: {{ message.created_on }} ({{ message.created_on|timesince }} ago)</p>
{% endblock %}